FROM ubuntu:18.04 AS builder
ARG third_party_flags='-yz'

# System Dependencies.
ARG BUILD_ID='local'
LABEL kpsr-thirdparties=builder
LABEL BUILD_ID=${BUILD_ID}

RUN apt update && apt-get install wget libssl-dev libcurl4-gnutls-dev build-essential git cmake -y --fix-missing

ENV TZ=Europe/Minsk
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /var/tmp

# Klepsydra
COPY . kpsr-thirdparties

RUN cd kpsr-thirdparties \
    && echo "./build_3parties.sh $third_party_flags" \
    && ./build_3parties.sh $third_party_flags


FROM ubuntu:18.04
LABEL kpsr-thirdparties=ZMQ

COPY --from=builder /opt/klepsydra/ /opt/klepsydra/
COPY --from=builder /usr/local/include/yaml-cpp/ /usr/local/include/yaml-cpp/
COPY --from=builder /usr/local/lib/cmake/yaml-cpp/ /usr/local/lib/cmake/yaml-cpp/
COPY --from=builder /usr/local/lib/libyaml* /usr/local/lib/

WORKDIR /opt/
